name = "Mixed Combat Pack"
uid = "b117ef40-2b6b-4596-96c5-0e8887ac0807"
url = "https://github.com/SmalkiGroove/mcp-mod"
version = 1
copyright = "FAF Community - I've done no unit model myself"
description = "Most complete unit pack (long download!). Full AI support and balanced."
author = "CSI"
icon = "/mods/MCP/mod_icon.dds"
selectable = true
enabled = true
exclusive = false
ui_only = false
special_thanks = "Uveso, Balthazar"
conflicts = {}